use serde::{Deserialize, Serialize};

/// https://developer.mozilla.org/en-US/docs/Web/API/UI_Events/Keyboard_event_key_values
pub fn mapping_key_event_to_code(key: String) -> Event {
    match key.as_str() {
        "Alt" => Event::VK_LMENU,
        "CapsLock" => Event::VK_CAPSLOCK,
        "Control" => Event::VK_LCONTROL,
        "Meta" => Event::VK_LWIN,
        "NumLock" => Event::VK_NUMLOCK,
        "ScrollLock" => Event::VK_SCROLLLOCK,
        "Shift" => Event::VK_LSHIFT,
        "Enter" => Event::VK_ENTER,
        "Tab" => Event::VK_TAB,
        " " => Event::VK_SPACE,
        "ArrowDown" => Event::VK_DOWN,
        "ArrowLeft" => Event::VK_LEFT,
        "ArrowRight" => Event::VK_RIGHT,
        "ArrowUp" => Event::VK_UP,
        "End" => Event::VK_END,
        "Home" => Event::VK_HOME,
        "PageDown" => Event::VK_PAGEDOWN,
        "PageUp" => Event::VK_PAGEUP,
        "Backspace" => Event::VK_BACKSPACE,
        "Clear" => Event::VK_CLEAR,
        "CrSel" => Event::VK_CRSEL,
        "Delete" => Event::VK_DELETE,
        "EraseEof" => Event::VK_EREOF,
        "ExSel" => Event::VK_EXSEL,
        "Insert" => Event::VK_INSERT,
        "Accept" => Event::VK_ACCEPT,
        "Attn" => Event::VK_ATTN,
        "Escape" => Event::VK_ESC,
        "Help" => Event::VK_HELP,
        "Pause" => Event::VK_PAUSE,
        "Play" => Event::VK_PLAY,
        "Select" => Event::VK_SELECT,
        "PrintScreen" => Event::VK_SNAPSHOT,
        "Convert" => Event::VK_CONVERT,
        "FinalMode" => Event::VK_FINAL,
        "ModeChange" => Event::VK_MODECHANGE,
        "NonConvert" => Event::VK_NONCONVERT,
        "Process" => Event::VK_PROCESSKEY,
        "HangulMode" => Event::VK_HANGUEL,
        "HanjaMode" => Event::VK_HANJA,
        "JunjaMode" => Event::VK_JUNJA,
        "KanaMode" => Event::VK_KANA,
        "KanjiMode" => Event::VK_KANJI,
        "F1" => Event::VK_F1,
        "F2" => Event::VK_F2,
        "F3" => Event::VK_F3,
        "F4" => Event::VK_F4,
        "F5" => Event::VK_F5,
        "F6" => Event::VK_F6,
        "F7" => Event::VK_F7,
        "F8" => Event::VK_F8,
        "F9" => Event::VK_F9,
        "F10" => Event::VK_F10,
        "F11" => Event::VK_F11,
        "F12" => Event::VK_F12,
        "F13" => Event::VK_F13,
        "F14" => Event::VK_F14,
        "F15" => Event::VK_F15,
        "F16" => Event::VK_F16,
        "F17" => Event::VK_F17,
        "F18" => Event::VK_F18,
        "F19" => Event::VK_F19,
        "F20" => Event::VK_F20,
        "MediaPlayPause" => Event::VK_MEDIA_PLAY_PAUSE,
        "MediaStop" => Event::VK_MEDIA_STOP,
        "MediaTrackNext" => Event::VK_MEDIA_NEXT_TRACK,
        "MediaTrackPrevious" => Event::VK_MEDIA_PREV_TRACK,
        "AudioVolumeDown" => Event::VK_VOLUME_DOWN,
        "AudioVolumeMute" => Event::VK_VOLUME_MUTE,
        "AudioVolumeUp" => Event::VK_VOLUME_UP,
        "ZoomToggle" => Event::VK_ZOOM,
        "Print" => Event::VK_PRINT,
        "LaunchMail" => Event::VK_LAUNCH_MAIL,
        "LaunchMediaSelect" => Event::VK_LAUNCH_MEDIA_SELECT,
        "LaunchApplication1" => Event::VK_LAUNCH_APP1,
        "LaunchApplication2" => Event::VK_LAUNCH_APP2,
        "BrowserBack" => Event::VK_BROWSER_BACK,
        "BrowserFavorites" => Event::VK_BROWSER_FAVORITES,
        "BrowserForward" => Event::VK_BROWSER_FORWARD,
        "BrowserHome" => Event::VK_BROWSER_HOME,
        "BrowserRefresh" => Event::VK_BROWSER_REFRESH,
        "BrowserSearch" => Event::VK_BROWSER_SEARCH,
        "BrowserStop" => Event::VK_BROWSER_STOP,
        "0" => Event::VK_0,
        "1" => Event::VK_1,
        "2" => Event::VK_2,
        "3" => Event::VK_3,
        "4" => Event::VK_4,
        "5" => Event::VK_5,
        "6" => Event::VK_6,
        "7" => Event::VK_7,
        "8" => Event::VK_8,
        "9" => Event::VK_9,
        "a" | "A" => Event::VK_A,
        "b" | "B" => Event::VK_B,
        "c" | "C" => Event::VK_C,
        "d" | "D" => Event::VK_D,
        "e" | "E" => Event::VK_E,
        "f" | "F" => Event::VK_F,
        "g" | "G" => Event::VK_G,
        "h" | "H" => Event::VK_H,
        "i" | "I" => Event::VK_I,
        "j" | "J" => Event::VK_J,
        "k" | "K" => Event::VK_K,
        "l" | "L" => Event::VK_L,
        "m" | "M" => Event::VK_M,
        "n" | "N" => Event::VK_N,
        "o" | "O" => Event::VK_O,
        "p" | "P" => Event::VK_P,
        "q" | "Q" => Event::VK_Q,
        "r" | "R" => Event::VK_R,
        "s" | "S" => Event::VK_S,
        "t" | "T" => Event::VK_T,
        "u" | "U" => Event::VK_U,
        "v" | "V" => Event::VK_V,
        "w" | "W" => Event::VK_W,
        "x" | "X" => Event::VK_X,
        "y" | "Y" => Event::VK_Y,
        "z" | "Z" => Event::VK_Z,
        "," | "<" => Event::VK_COMMA,
        "." | ">" => Event::VK_DOT,
        "/" | "?" => Event::VK_SLASH,
        ";" | ":" => Event::VK_SEMICOLON,
        "'" | "\"" => Event::VK_APOSTROPHE,
        "`" | "~" => Event::VK_GRAVE,
        "[" | "{" => Event::VK_LEFTBRACE,
        "\\" | "|" => Event::VK_BACKSLASH,
        "]" | "}" => Event::VK_RIGHTBRACE,
        "-" | "_" => Event::VK_MINUS,
        "=" | "+" => Event::VK_EQUAL,

        _ => Event::UNIDENTIFIED,
    }
}

#[derive(Serialize, Deserialize)]
pub struct Message {
    pub event: u8,
    pub payload: Option<Payload>,
}

#[derive(Serialize, Deserialize)]
pub struct Payload {
    pub p1: i32,
    pub p2: i32,
    pub p3: i32,
}

#[allow(non_camel_case_types)]
pub enum Event {
    // Keyboard
    VK_SHIFT,
    VK_CTRL,
    VK_ALT,
    VK_LSHIFT,
    VK_RSHIFT,
    VK_LCONTROL,
    VK_RCONTROL,
    VK_LWIN,
    VK_RWIN,
    KEYEVENTF_KEYUP,
    KEYEVENTF_SCANCODE,
    VK_SP1,
    VK_SP2,
    VK_SP3,
    VK_SP4,
    VK_SP5,
    VK_SP6,
    VK_SP7,
    VK_SP8,
    VK_SP9,
    VK_SP10,
    VK_SP11,
    VK_SP12,
    VK_ESC,
    VK_1,
    VK_2,
    VK_3,
    VK_4,
    VK_5,
    VK_6,
    VK_7,
    VK_8,
    VK_9,
    VK_0,
    VK_Q,
    VK_W,
    VK_E,
    VK_R,
    VK_T,
    VK_Y,
    VK_U,
    VK_I,
    VK_O,
    VK_P,
    VK_A,
    VK_S,
    VK_D,
    VK_F,
    VK_G,
    VK_H,
    VK_J,
    VK_K,
    VK_L,
    VK_Z,
    VK_X,
    VK_C,
    VK_V,
    VK_B,
    VK_N,
    VK_M,
    VK_F1,
    VK_F2,
    VK_F3,
    VK_F4,
    VK_F5,
    VK_F6,
    VK_F7,
    VK_F8,
    VK_F9,
    VK_F10,
    VK_F11,
    VK_F12,
    VK_F13,
    VK_F14,
    VK_F15,
    VK_F16,
    VK_F17,
    VK_F18,
    VK_F19,
    VK_F20,
    VK_F21,
    VK_F22,
    VK_F23,
    VK_F24,
    VK_NUMLOCK,
    VK_SCROLLLOCK,
    VK_RESERVED,
    VK_MINUS,
    VK_EQUAL,
    VK_BACKSPACE,
    VK_TAB,
    VK_LEFTBRACE,
    VK_RIGHTBRACE,
    VK_ENTER,
    VK_SEMICOLON,
    VK_APOSTROPHE,
    VK_GRAVE,
    VK_BACKSLASH,
    VK_COMMA,
    VK_DOT,
    VK_SLASH,
    VK_KPASTERISK,
    VK_SPACE,
    VK_CAPSLOCK,
    VK_KP0,
    VK_KP1,
    VK_KP2,
    VK_KP3,
    VK_KP4,
    VK_KP5,
    VK_KP6,
    VK_KP7,
    VK_KP8,
    VK_KP9,
    VK_KPMINUS,
    VK_KPPLUS,
    VK_KPDOT,
    VK_LBUTTON,
    VK_RBUTTON,
    VK_CANCEL,
    VK_MBUTTON,
    VK_XBUTTON1,
    VK_XBUTTON2,
    VK_BACK,
    VK_CLEAR,
    VK_PAUSE,
    VK_CAPITAL,
    VK_KANA,
    VK_HANGUEL,
    VK_HANGUL,
    VK_JUNJA,
    VK_FINAL,
    VK_HANJA,
    VK_KANJI,
    VK_CONVERT,
    VK_NONCONVERT,
    VK_ACCEPT,
    VK_MODECHANGE,
    VK_PAGEUP,
    VK_PAGEDOWN,
    VK_END,
    VK_HOME,
    VK_LEFT,
    VK_UP,
    VK_RIGHT,
    VK_DOWN,
    VK_SELECT,
    VK_PRINT,
    VK_EXECUTE,
    VK_SNAPSHOT,
    VK_INSERT,
    VK_DELETE,
    VK_HELP,
    VK_SCROLL,
    VK_LMENU,
    VK_RMENU,
    VK_BROWSER_BACK,
    VK_BROWSER_FORWARD,
    VK_BROWSER_REFRESH,
    VK_BROWSER_STOP,
    VK_BROWSER_SEARCH,
    VK_BROWSER_FAVORITES,
    VK_BROWSER_HOME,
    VK_VOLUME_MUTE,
    VK_VOLUME_DOWN,
    VK_VOLUME_UP,
    VK_MEDIA_NEXT_TRACK,
    VK_MEDIA_PREV_TRACK,
    VK_MEDIA_STOP,
    VK_MEDIA_PLAY_PAUSE,
    VK_LAUNCH_MAIL,
    VK_LAUNCH_MEDIA_SELECT,
    VK_LAUNCH_APP1,
    VK_LAUNCH_APP2,
    VK_OEM_1,
    VK_OEM_PLUS,
    VK_OEM_COMMA,
    VK_OEM_MINUS,
    VK_OEM_PERIOD,
    VK_OEM_2,
    VK_OEM_3,
    VK_OEM_4,
    VK_OEM_5,
    VK_OEM_6,
    VK_OEM_7,
    VK_OEM_8,
    VK_OEM_102,
    VK_PROCESSKEY,
    VK_PACKET,
    VK_ATTN,
    VK_CRSEL,
    VK_EXSEL,
    VK_EREOF,
    VK_PLAY,
    VK_ZOOM,
    VK_NONAME,
    VK_PA1,
    VK_OEM_CLEAR,

    // Mouse
    MOUSEEVENTF_MOVE,
    MOUSEEVENTF_LEFTDOWN,
    MOUSEEVENTF_LEFTUP,
    MOUSEEVENTF_RIGHTDOWN,
    MOUSEEVENTF_RIGHTUP,
    MOUSEEVENTF_MIDDLEDOWN,
    MOUSEEVENTF_MIDDLEUP,
    MOUSEEVENTF_XDOWN,
    MOUSEEVENTF_XUP,
    MOUSEEVENTF_WHEEL,
    MOUSEEVENTF_HWHEEL,
    MOUSEEVENTF_ABSOLUTE,

    // Unidentified key
    UNIDENTIFIED,

    // Custom
    CLIPBOARD,
}
