name: Lindows CI

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    just:
        runs-on: windows-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install just
              run: choco install just

            - name: Set up Go
              uses: actions/setup-go@v5
              with:
                  go-version: 1.22

            - name: Run just
              run: just
