[build]
target = "./index.html"

[watch]
ignore = ["./src-tauri"]

[serve]
address = "127.0.0.1"
port = 1420
open = false

[tools]
wasm_bindgen = "0.2.92"
wasm_opt = "version_116"
tailwindcss = "3.4.1"
